Repository jenkinsci/maven-plugin, pull requests merged in 2021-01, with the labels that each got.

#155 Move tests that depend on MavenModuleSet and MavenModuleSetBuild from Jenkins core to Maven Integration
  src/test/java/hudson/bugs/seasar/Operation2174Test.java
  src/test/java/hudson/cli/ListJobsCommandTest.java
  src/test/java/hudson/model/JobPropertyTest.java
  src/test/java/hudson/model/NodeTest.java
  src/test/java/hudson/tools/ToolLocationNodePropertyTest.java
  src/test/java/jenkins/model/JenkinsBuildsAndWorkspacesDirectoriesTest.java
  src/test/java/jenkins/tasks/SimpleBuildWrapperTest.java
  src/test/java/lib/hudson/ListScmBrowsersTest.java
  src/test/resources/hudson/model/JobPropertyTest/JobPropertyImpl/summary.jelly
Labels: chore, tests

#157 Update forms for tables-to-divs
  src/main/resources/hudson/maven/MavenModuleSet/configure-entries.jelly
  src/main/resources/hudson/maven/MavenTestDataPublisher/config.jelly
  src/main/resources/lib/maven/blockWrapper.jelly
Labels: chore

#159 parent 2.270 for table to div change
  pom.xml
Labels: chore

#160 upgrade bom to 2.263.x
  pom.xml
Labels: dependencies, java
