Repository jenkinsci/maven-plugin, pull requests merged in 2022-09, with the labels that each got.

#287 bump parent pom from 4.40 to 4.47
  pom.xml
Labels: dependencies

#288 Upgrade wagon 3.5.2 and remove all com.jcraft. proxy artifacts
  pom.xml
Labels: dependencies, removed

#290 Replace wiki references with inline content
  CHANGELOG.md
  README.md
Labels: documentation
